### ISSUE TITLE
 Couldn't open /usr/local/freeswitch/conf/freeswitch.xml (No such file or directory)

### ISSUE THREAD

**Issue by Curisan** [rts-cn/xswitch-free#14]
I enter the container and can't find /usr/local/freeswitch/conf/freeswitch.xml. The log is below:
xswitch-free | Cannot Initialize [Cannot Open log directory or XML Root!]
xswitch-free | 2022-07-26 11:28:41.888183 0.00% [INFO] switch_event.c:713 Activate Eventing Engine.
xswitch-free | 2022-07-26 11:28:41.904952 0.00% [WARNING] switch_event.c:683 Create additional event dispatch thread 0
xswitch-free | 2022-07-26 11:28:41.905239 0.00% [ERR] switch_xml.c:1423 Couldn't open /usr/local/freeswitch/conf/freeswitch.xml (No such file or directory)
xswitch-free | ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
xswitch-free | ERROR: Could not set nice level
xswitch-free | Cannot Initialize [Cannot Open log directory or XML Root!]
xswitch-free | 2022-07-26 11:28:41.945563 0.00% [INFO] switch_event.c:713 Activate Eventing Engine.
xswitch-free | 2022-07-26 11:28:41.962755 0.00% [WARNING] switch_event.c:683 Create additional event dispatch thread 0
xswitch-free | 2022-07-26 11:28:41.963036 0.00% [ERR] switch_xml.c:1423 Couldn't open /usr/local/freeswitch/conf/freeswitch.xml (No such file or directory)
xswitch-free | ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
xswitch-free | ERROR: Could not set nice level
xswitch-free | Cannot Initialize [Cannot Open log directory or XML Root!]
xswitch-free | 2022-07-26 11:28:42.004287 0.00% [INFO] switch_event.c:713 Activate Eventing Engine.
xswitch-free | 2022-07-26 11:28:42.021237 0.00% [WARNING] switch_event.c:683 Create additional event dispatch thread 0
xswitch-free | 2022-07-26 11:28:42.021526 0.00% [ERR] switch_xml.c:1423 Couldn't open /usr/local/freeswitch/conf/freeswitch.xml (No such file or directory)
xswitch-free | ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
xswitch-free | ERROR: Could not set nice level
xswitch-free | Cannot Initialize [Cannot Open log directory or XML Root!]
xswitch-free | 2022-07-26 11:28:42.060790 0.00% [INFO] switch_event.c:713 Activate Eventing Engine.
xswitch-free | 2022-07-26 11:28:42.078212 0.00% [WARNING] switch_event.c:683 Create additional event dispatch thread 0
xswitch-free | 2022-07-26 11:28:42.078491 0.00% [ERR] switch_xml.c:1423 Couldn't open /usr/local/freeswitch/conf/freeswitch.xml (No such file or directory)
xswitch-free | ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
xswitch-free | ERROR: Could not set nice level

**Comment by lwj-java** [comment]
+1 镜像中没有配置啊

**Comment by lwj-java** [comment]
可以自己把配置挂在到容器里就好了

**Comment by seven1240** [comment]
镜像中默认是有的。什么版本？docker pull 一下，然后看看你用的版本是什么。

docker image ls ccr.ccs.tencentyun.com/xswitch/xswitch-free
REPOSITORY                                    TAG       IMAGE ID       CREATED        SIZE
ccr.ccs.tencentyun.com/xswitch/xswitch-free   latest    30669bd48113   4 days ago     511MB

**Comment by seven1240** [comment]
试下最新的版本，有问题再开。
