### ISSUE TITLE
这是漏洞吗? 

### ISSUE THREAD

**Issue by Jett1993** [rts-cn/xswitch-free#16]
在公网用docker部署的, 用的国内的服务器, 日志一直打印如下信息: 

2022-12-02 16:29:42.759838 100.00% [NOTICE] switch_core_state_machine.c:387 sofia/public/100@126.60.31.215 has executed the last dialplan instruction, hanging up.
2022-12-02 16:29:42.759838 100.00% [NOTICE] switch_core_state_machine.c:389 Hangup sofia/public/100@126.60.31.215 [CS_EXECUTE] [NORMAL_CLEARING]
2022-12-02 16:29:42.759838 100.00% [NOTICE] switch_core_session.c:1772 Session 470 (sofia/public/100@126.60.31.215) Ended
2022-12-02 16:29:42.759838 100.00% [NOTICE] switch_core_session.c:1776 Close Channel sofia/public/100@126.60.31.215 [CS_DESTROY]
2022-12-02 16:29:58.099838 100.00% [NOTICE] switch_channel.c:1123 New Channel sofia/public/100@126.60.31.215 [b03a835d-5254-44f3-8058-c50c374a613f]
2022-12-02 16:29:58.119837 100.00% [INFO] sofia.c:10726 sofia/public/100@126.60.31.215 receiving invite from 45.93.16.168:52565 version: 1.10.9-dev git 356d3f9 2022-11-23 07:22:41Z 64bit call-id=1837907722-907793008-479755714
2022-12-02 16:29:58.119837 100.00% [INFO] mod_dialplan_xml.c:639 Processing 100 <100>->802985750117 in context public
EXECUTE [depth=0] sofia/public/100@126.60.31.215 info()
2022-12-02 16:29:58.119837 100.00% [INFO] mod_dptools.c:1886 CHANNEL_DATA:
Channel-State: [CS_EXECUTE]
Channel-Call-State: [RINGING]
Channel-State-Number: [4]
Channel-Name: [sofia/public/100@126.60.31.215]
Unique-ID: [b03a835d-5254-44f3-8058-c50c374a613f]
Call-Direction: [inbound]
Presence-Call-Direction: [inbound]
Channel-HIT-Dialplan: [true]
Channel-Call-UUID: [b03a835d-5254-44f3-8058-c50c374a613f]
Answer-State: [ringing]
Channel-Read-Codec-Name: [PCMU]
Channel-Read-Codec-Rate: [8000]
Channel-Read-Codec-Bit-Rate: [64000]
Channel-Write-Codec-Name: [PCMU]
Channel-Write-Codec-Rate: [8000]
Channel-Write-Codec-Bit-Rate: [64000]
Caller-Direction: [inbound]
Caller-Logical-Direction: [inbound]
Caller-Username: [100]
Caller-Dialplan: [XML]
Caller-Caller-ID-Name: [100]
Caller-Caller-ID-Number: [100]
Caller-Orig-Caller-ID-Name: [100]
Caller-Orig-Caller-ID-Number: [100]
Caller-Network-Addr: [45.93.16.168]
Caller-ANI: [100]
Caller-Destination-Number: [802985750117]
Caller-Unique-ID: [b03a835d-5254-44f3-8058-c50c374a613f]
Cller-Source: [mod_sofia]
Caller-Context: [public]
Caller-Channel-Name: [sofia/public/100@126.60.31.215]
Caller-Profile-Index: [1]
Caller-Profile-Created-Time: [1669969798119837]
Caller-Channel-Created-Time: [1669969798119837]
Caller-Channel-Answered-Time: [0]
Caller-Channel-Progress-Time: [0]
Caller-Channel-Progress-Media-Time: [0]
Caller-Channel-Hangup-Time: [0]
Caller-Channel-Transfer-Time: [0]
Caller-Channel-Resurrect-Time: [0]
Caller-Channel-Bridged-Time: [0]
Caller-Channel-Last-Hold: [0]
Caller-Channel-Hold-Accum: [0]
Caller-Screen-Bit: [true]
Caller-Privacy-Hide-Name: [false]
Caller-Privacy-Hide-Number: [false]
variable_direction: [inbound]
variable_uuid: [b03a835d-5254-44f3-8058-c50c374a613f]
variable_session_id: [471]
variable_sip_from_user: [100]
variable_sip_from_uri: [100@126.60.31.215]
variable_sip_from_host: [126.60.31.215]
variable_video_media_flow: [disabled]
variable_text_media_flow: [disabled]
variable_channel_name: [sofia/public/100@126.60.31.215]
variable_sip_call_id: [1837907722-907793008-479755714]
variable_sip_local_network_addr: [126.60.31.215]
variable_sip_network_ip: [45.93.16.168]
variable_sip_network_port: [52565]
variable_sip_invite_stamp: [1669969798119837]
variable_sip_received_ip: [45.93.16.168]
variable_sip_received_port: [52565]
variable_sip_via_protocol: [udp]
variable_sip_from_user_stripped: [100]
variable_sip_from_tag: [502304453]
variable_sofia_profile_name: [public]
variable_sofia_profile_url: [sip:mod_sofia@126.60.31.215:5080]
variable_recovery_profile_name: [public]
variable_sip_full_via: [SIP/2.0/UDP 45.93.16.168:52565;branch=z9hG4bK598503429]
variable_sip_full_from: [<sip:100@126.60.31.215>;tag=502304453]
variable_sip_full_to: [<sip:802985750117@126.60.31.215>]
variable_sip_allow: [ACK, BYE, CANCEL, INFO, INVITE, MESSAGE, NOTIFY, OPTIONS, PRACK, REFER, REGISTER, SUBSCRIBE, UPDATE, PUBLISH]
variable_sip_req_user: [802985750117]
variable_sip_req_uri: [802985750117@126.60.31.215]
variable_sip_req_host: [126.60.31.215]
variable_sip_to_user: [802985750117]
variable_sip_to_uri: [802985750117@126.60.31.215]
variable_sip_to_host: [126.60.31.215]
variable_sip_contact_user: [100]
variable_sip_contact_port: [52565]
variable_sip_contact_uri: [100@45.93.16.168:52565]
variable_sip_contact_host: [45.93.16.168]
variable_sip_user_agent: [Linksys-SPA942]
variable_sip_via_host: [45.93.16.168]
variable_sip_via_port: [52565]
variable_max_forwards: [70]
variable_switch_r_sdp: [v=0
o=100 16264 18299 IN IP4 192.168.1.83
s=call
c=IN IP4 192.168.1.83
t=0 0
m=audio 25282 RTP/AVP 0 101
a=rtpmap:0 pcmu/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-11
a=sendrecv
]
variable_ep_codec_string: [CORE_PCM_MODULE.pcmu@8000h@20i@64000b]
variable_rtp_use_codec_string: [PCMA,PCMU,G722,OPUS]
variable_remote_video_media_flow: [inactive]
variable_remote_text_media_flow: [inactive]
variable_remote_audio_media_flow: [sendrecv]
variable_audio_media_flow: [sendrecv]
variable_remote_media_ip: [192.168.1.83]
variable_remote_media_port: [25282]
variable_rtp_audio_recv_pt: [0]
variable_rtp_use_codec_name: [PCMU]
variable_rtp_use_codec_rate: [8000]
variable_rtp_use_codec_ptime: [20]
variable_rtp_use_codec_channels: [1]
variable_rtp_last_audio_codec_string: [PCMU@8000h@20i@1c]
variable_read_codec: [PCMU]
variable_original_read_codec: [PCMU]
variable_read_rate: [8000]
variable_original_read_rate: [8000]
variable_write_codec: [PCMU]
variable_write_rate: [8000]
variable_dtmf_type: [rfc2833]
variable_endpoint_disposition: [RECEIVED]
variable_first_dialplan_context: [public]
variable_first_dest_number: [802985750117]
variable_call_uuid: [b03a835d-5254-44f3-8058-c50c374a613f]
variable_current_application: [info]

**Comment by seven1240** [comment]
可能是有人扫描你的服务器，跟本Docker无关，你需要配置安全策略。
