### ISSUE TITLE
XSwitch转发功能概率没执行问题

### ISSUE THREAD

**Issue by WZHCM** [rts-cn/xswitch-free#17]
简述：出现异常的包位置在410510和410539。可以直接看到SIP客户端发了MESSAGE后，Xswitch没有进行转发。概率出现

关于代码实现
采用XSwitch找不到匹配规则时候，默认使用转发。
92和91是这次的群发的lua脚本。
![image](https://user-images.githubusercontent.com/34757448/207565072-1b2e0ef4-92b7-41a0-93aa-b42cddf0b87a.png)
想问下这个默认转发可不可以写到这个default里面。因为有执行的92和91是正常使用的

详细描述：
正常的流程：（正常和异常都在一个抓包里面）
业务场景：
Sip客户端发送“92+组号”的MESSAGE给XSwitch，把MESSAGE逐个发送给组里面的SIP客户端。SIP客户端收到MESSAGE后，会弹出一个按钮。按了按钮后，会发送MESSAGE回复给一开始发送的SIP客户端。
![image](https://user-images.githubusercontent.com/34757448/207564779-add5b1f1-6dd7-483e-90de-7bab303ff282.png)

例如这里101010799发送92110的MESSAGE，然后XSwitch分别发送给了组里面对应的sip客户端。包的位置在92436
 

然后组里面有一台设备进行了响应。
![image](https://user-images.githubusercontent.com/34757448/207565192-8a325ba6-7306-44e4-afea-a57f4ae50315.png)

XSwitch转发MESSAGE
![image](https://user-images.githubusercontent.com/34757448/207565232-fba52c62-afa7-4c8f-abf5-42114df16455.png)

正常的整个流程结束，经过不到1秒时间。

 
**异常的部分：（前半部分都是正常，问题在XSwitch转发没有执行）**
101010316发送92602后XSwitch分别进行发送。包的位置在410468
 
![image](https://user-images.githubusercontent.com/34757448/207565347-ad8cd35d-68b0-469a-b838-6056482b6933.png)

然后组里面有设备进行了响应。
 
![image](https://user-images.githubusercontent.com/34757448/207565393-e7fd7005-17e3-4e79-988c-59fbb128486b.png)

但是按照正常流程，这时候XSwitch应该转发MESSAGE。抓包上却没有发现XSwitch做出了转发。
这个现象是概率出现，如果现场设备交互比较多时候，出现概率会比较高。

**Comment by WZHCM** [comment]
[抓包192.168.0.160是服务器.zip](https://github.com/rts-cn/xswitch-free/files/10226666/192.168.0.160.zip)

**Comment by seven1240** [comment]
看不明白，你应该提供XSwitch的日志。另外，你那个101010316有路由吗？即使92，91是好的，1010为什么不配个路由？Lua脚本写的是什么？一头雾水。

**Comment by seven1240** [comment]
试试最新的版本，有问题再开吧。
